### ISSUE TITLE
Macro and header names are too plain and conflict easily

### ISSUE THREAD

**Issue by rcdailey** [aantron/better-enums#11]
A macro named `ENUM` is a prime candidate for easy symbol ambiguity. And in my code base, I am seeing this. This requires me to do silly inclusion trickery like so:

```
// All normal includes at the top

#undef ENUM
#include <enum.h> // This one must be last in the list of include directives

ENUM(Fubar, int, One, Two, Three);
```

The best solution to this would be to make a more generic name for your macros. Boost does this by prefixing macros consistently. This makes them a bit more verbose, but it's a necessary annoyance when dealing with macros. I think maybe a name like `BETTER_ENUM()` would work just fine.

The include is odd as well. I am free to nest your header file in any directory I want, so I can resolve the issue that way. But "out of the box" your solution implies you include `enum.h` directly. Instead, I think you should nest your includes to avoid ambiguous includes:

```
#include <better/enum.h>
```

This might require restructuring your repository a bit, to make it obvious to people that the include is supposed to be done in a relative way like I've shown above.

**Comment by aantron** [comment]
The first change seems reasonable to do now. It would be nice to get the opinions of more users first, but I am not sure how to solicit them.

I'll probably hold off on the second. Users are still free to put `enum.h` in a subdirectory of their choosing, as you mentioned. I may nest `enum.h` in a `better-enums` subdirectory later, if the header gets split into multiple files, or if there are a lot of "extras" to distribute. I do already have such a `better-enums` directory – it's just not first-class, since the only thing there is the C++17 demo.

**Comment by rcdailey** [comment]
The file nesting isn't that important, it was a side-suggestion. Let's drop that off the plate for now to keep the discussion more focused.

Concerning the macro name, I'd argue that doesn't require feedback at all. Simple macro names are notorious for conflicting with symbols. It's a non-decision to rename it. I think if you expect your library to be used in professional, production code which has millions of lines of code and numerous incoming dependencies, the rename will be an absolute requirement.

Again, I'd like to refer you to the [Boost.Preprocessor](http://www.boost.org/doc/libs/1_59_0/libs/preprocessor/doc/) library. You'll notice they prefix all macros with `BOOST_PP`. This is akin to a namespace in the macro world, as you know. The verbosity and "extra characters to type" tradeoff is well worth the guarantee that your library will work out-of-the-box in most (if not all) code bases regardless of size and number of dependencies.

**Comment by aantron** [comment]
As I said, I am in favor of changing the macro name. I merely added that it would be nice to get additional feedback, since a large number of people seem to have been fine with `ENUM`, and also for good ideas for a replacement name that only 2 people (us) might not come up with. However, I won't be waiting for feedback, since I don't have an efficient way of getting it at this point. I will do this change together with the other changes we are currently discussing.

**Comment by rcdailey** [comment]
I like the name `ENUM` too, honestly if there was no conflict the name is perfect. But scattering the `#undef`'s all over our code base would quickly land me lots of ugly looks from my coworkers in my code reviews :-)

Thanks for welcoming my feedback, you've done a great job.
