### ISSUE TITLE
Can and ENUM-declared enum be a member variable type?

### ISSUE THREAD

**Issue by matsbror** [aantron/better-enums#43]
It seems it cannot, As soon as I declare a member variable of a BETTER_ENUM, say Colour,  the compiler says:

    error: ‘Colour::Colour()’ is private within this context

and the constructor of the class where it is declared becomes deleted.

Any ideas?

**Comment by matsbror** [comment]
Sorry, I just saw that you wrote this as a limitation. Sorry for that.

**Comment by aantron** [comment]
No worries.

I'm not sure what the question was, though:

1. Can you declare a `BETTER_ENUM` as a member type?

    ```
    class Class {
        BETTER_ENUM(Foo, int, Bar)
    };
    ```

2. Can you have a member variable of a `BETTER_ENUM` type?

    ```
    BETTER_ENUM(Foo, int, Bar)

    class Class {
        Foo foo;
    };
    ```

The first one is not (currently) possible, and this is the [limitation](https://github.com/aantron/better-enums#limitations) I believe we are referring to.

The second one is possible. However, due to the current design of Better Enums, you need to either

1. Initialize the `BETTER_ENUM` member (`foo` above) with some value in all of your constructors (of `Class` above).
2. Give the `BETTER_ENUM` `Foo` a default constructor as described [here](http://aantron.github.io/better-enums/OptInFeatures.html#DefaultConstructors).

See #10 for some discussion of default constructors and Better Enums, and your input is welcome. It has been a long time since we considered it, and maybe a fresh view is good.
