### ISSUE TITLE
Enum class values are implicitly converted to integers

### ISSUE THREAD

**Issue by onqtam** [aantron/better-enums#7]
Hi

just a question: can such conversions be disabled somehow (like with enum class from c++11)

```C++
int a = Words::Hello;
```

This would be very useful - even if it is enabled only with a define before the inclusion of the enum header.

Also with enum classes we can forward declare them and even make a value out of them (if not using the enum values)
```C++
enum class A;
A op;
```

and with your library an enum can be forward declared like this ```class Words;``` but cannot be used for a value - only for refs and pointers (because it's a class...) - this is not that much of an issue though

**Comment by aantron** [comment]
Hi,

Yes, I believe defining `BETTER_ENUMS_STRICT_CONVERSION` before including `enum.h` will do what you want. Please let me know if not :) I am still open to the idea of making this the default, but [this page](http://aantron.github.io/better-enums/OptInFeatures.html#StrictConversions) has some discussion on why I haven't done so yet.

As for the second part, I don't think there is a really nice way to get this functionality with Better Enums as classes. I did previously maintain a variant where the macro declared an enum and a trait, like this:

~~~
enum class Words : int { Hello, World }
template <>
struct enum_traits<Words> { ... };
~~~

That would make it possible to use `Words` exactly like a normal enum (since that's what it would be). There is a discussion of this [here](http://aantron.github.io/better-enums/DesignDecisionsFAQ.html#ShouldBetterEnumsProvideEnum) and an old implementation [here](https://github.com/aantron/better-enums/tree/traits). I decided not to do this because of some drawbacks this approach has, but I am always interested in knowing how important you and other people consider the various drawbacks and benefits to be :)

**Comment by onqtam** [comment]
Oh - so it is another case of RTFM... sry about that :)
Cool library though - will use it

**Comment by aantron** [comment]
No problem, thanks, and enjoy :)
