### ISSUE TITLE
Recommend magic_enum?

### ISSUE THREAD

**Issue by aantron** [aantron/better-enums#78]
See https://github.com/Neargye/magic_enum#readme.

If someone tries both Better Enums and magic_enum, and there is a reason to prefer Better Enums, please leave a comment here.

Otherwise, I think we should recommend magic_enum and move Better Enums toward deprecation.

cc @Neargye

**Comment by heyx3** [comment]
From what I understand, magic_enum requires that your enums cover a contiguous range? That's a big dealbreaker for me; I'm creating numerous enums whose values correspond to various OpenGL tokens which span a broad, sparse range of uint32 values. For example, an enum of all the depth test modes, an enum of all the blending factors, an enum of the different stencil write modes...

It's also a notable that magic_enum depends on non-standard compiler features, even if all the common compilers are supported.

**Comment by aantron** [comment]
IIRC the range doesn't have to be contiguous, magic_enum just weakly "prefers" for it to be dense (but gaps are possible), and relatively limited by default. I recommend trying it/asking at the magic_enum. Would be interested to know what you find out.

**Comment by Neargye** [comment]
Hi @heyx3,
You can familiarize yourself with the magic_enum limitations https://github.com/Neargye/magic_enum/blob/master/doc/limitations.md.

Summary:
* Sparse range enum - ok. For a dense enum, it can produce more optimized structures.
* There is a default range of search enum values. You can define your range for enum, for example, if it is large.
* The library supports three major compilers.
* There is also a separate setting for working with enum flags.

Also, could you give an example of enums?

**Comment by heyx3** [comment]
@Neargye these are the most sparse ones I currently have, all of which can be found here: https://github.com/heyx3/B-plus/blob/master/Engine/Renderer/Helpers.h

Face culling modes:
GL_INVALID_ENUM: 0x0500 (to represent "disable culling")
GL_BACK: 0x0405
GL_FRONT: 0x0404
GL_FRONT_AND_BACK: 0x0408

Stencil buffer operations:
GL_ZERO: 0
GL_KEEP: 0x1E00
GL_REPLACE: 0x1E01
GL_INCR: 0x1E02
GL_DECR: 0x1E03
GL_INVERT: 0x150A
GL_INCR_WRAP: 0x8507
GL_DECR_WRAP: 0x8508

Blend factors:
GL_ZERO: 0
GL_ONE: 1
GL_SRC_COLOR: 0x0300
GL_ONE_MINUS_SRC_COLOR: 0x0301
GL_SRC_ALPHA:0x0302
GL_ONE_MINUS_SRC_ALPHA: 0x0303
GL_DST_ALPHA: 0x0304
GL_ONE_MINUS_DST_ALPHA: 0x0305
GL_DST_COLOR: 0x0306
GL_ONE_MINUS_DST_COLOR: 0x0307
GL_CONSTANT_COLOR: 0x8001
GL_ONE_MINUS_CONSTANT_COLOR: 0x8002
GL_CONSTANT_ALPHA: 0x8003
GL_ONE_MINUS_CONSTANT_ALPHA: 0x8004

**Comment by heyx3** [comment]
And to be clear, I'm not saying it's automatically bad that magic_enum relies on non-standard features; just that there are developers out there who are stuck on other compilers for various reasons and won't be able to use those features, and so this is a legitimate selling point for better-enums.

**Comment by Neargye** [comment]
I absolutely agree about the limitation of non-standard features and C++ versions.
Also, magic_enum does not pretend to be a silver bullet, it was originally developed for enums from my work.

The ideal option is a reflection that may someday be added to the C++ standard.

**Comment by Neargye** [comment]
I will repeat here some conclusions from the last discussion.

Both libraries solve similar problems, but with a different implementation.

Difference:

Better Enums:
* Need registered enum by the macro.
* C++98 or higher.
* Not using non-standard features.

Magic Enums:
* Small enum does not need to be registered by a macro.
  If the default range does not fit, you can register a new range through templates or a macro.
* C++17 or higher.
* Uses a compiler-specific hack (based on __PRETTY_FUNCTION__ / __FUNCSIG__).
  Clang >= 5, MSVC >= 15.3 and GCC >= 9. Only since this GCC version support intrinsics PRETTY_FUNCTION to get enum name.

**Comment by SwissFrank** [comment]
Hello Neargye, Aantron:

I like both packages.  Thank you both for your contributions to the user community!  Magic is of course a little bit slicker.  But we're in the community that can't use it: our production environment uses a Red Hat that doesn't support gcc9, and that won't change just so we can use Magic.

I also have a fear that the compiler-specific hack needed for gcc may not last.  Any chance gcc, clang etc. may discontinue this hack, or do you think your package has enough interest within the compiler developer's community that they'll keep it  compatible in order to avoid hurting your user community?

Can you describe what information precisely you're getting from this hack?  Is it something I could provide manually e.g. with a macro?  If so I'd like that approach.  I've tried reading your files and to be honest I'm not quite advanced enough at modern/complicated C++ to follow easily.

**Comment by Neargye** [comment]
Hi @SwissFrank,
`magic_enum` uses a compiler-specific hack (based on `__PRETTY_FUNCTION__`/ `__FUNCSIG__`), which works on Clang >= 5, MSVC >= 15.3 and GCC >= 9.

For more info see https://github.com/Neargye/magic_enum/blob/master/doc/limitations.md

> I also have a fear that the compiler-specific hack needed for gcc may not last.
This hack is quite ancient, it’s just that gcc fixed the `__PRETTY_FUNCTION__` for enums quite recently, on gcc >= 9.

**Comment by SwissFrank** [comment]
Hi Neargye, yes, I've read the public materials and knew all that.  I was just wondering about the very specific usage of the variable.  Of course I can "simply look at the code..."

OK, I see that __PRETTY_FUNCTION__ doesn't do something that is so specialized that magic_enum code might fail to work in the future.  It is simply outputting a template specialization's full name, and you're supplying the enum to the template specialization so it gets captured in a string.  Even if/when the exact formatting of that specialized template name changes in the future (e.g., maybe they delete "with" in gcc 10.0) it's inconceivable that they'd have the pretty name of a template expansion NOT include the variables it's being expanded with.  So, I think I can write code with magic_enum and have confidence it will work for 20 years, even it may from time to time require a tweak to the specific offsets in  __PRETTY_FUNCTION__ used to find the enum names in the example above.

**Comment by Neargye** [comment]
@SwissFrank,
I can not guarantee that the cat will work without changes, it depends on the compiler extensions.

But I have several options for compatibility:

* A variable that indicates whether the library is supported.
* If it is no longer supported on some compiler version, an error will occur.
* CI for test different compiler version (GCC, Clang, MSVC).
