### ISSUE TITLE
Usage inside a class

### ISSUE THREAD

**Issue by X-Ryl669** [aantron/better-enums#8]
You can do something like this:
```


// Make sure it's possible to compare string correctly
constexpr bool static_strequal_helper(const char * a, const char * b, unsigned len) {
   return (len == 0) ? true : ((*a == *b) ? static_strequal_helper(a + 1, b + 1, len - 1) : false);
}

// This is the base class using CRTP for capturing the enum' class type
// With the macro trick below, it allow auto registration even in classes of your enum, and 
// also O(1) runtime string lookup-to-value matching
template <typename T>
struct CatalogEnum
{
     typedef T ClassType;
     static std::map<const char *, int> enumToValue; 
     static void registerField(const char * name, int value) { enumToValue[name] = value; }
     static int fromStringImpl(const char * name) { return enumToValue[name]; }
};

/* This is the basic block. Because your enum derives from CatalogEnum, it has a registerField member, so it can be registered at run time (before any usage)
Also, I've provided a basic constexpr trick to match against an enum value, but not the code 
for complete lookup. 
It should not be difficult to iterate over all the RegisterEnum entries at compile time to perform O(N) lookup for a fromString method. 
Please notice that even if you enum as same value for 2 field, it'll generate two different instance of this
template, and will still work correctly, since the pointer to _get_field_name is different */ 
template <typename Class, int value, typename const char* (*enumName)()>
struct RegisterEnum
{
      // Compile-time version
      template<size_t N>
      constexpr bool match_string(const char (&a)[N]) const { return static_strequal_helper(a, (*enumName)(), N); }
      // Run-time version
      bool match_string(const char* a) const { return strcmp(a, (*enumName)()) == 0; }

      RegisterEnum() { CatalogEnum<Class>::registerField((*enumName)(), value); }
};

// Basic macro trick, it declares a static function, and uses its address as a templated differentiator
// Then the templated object constructor takes care of calling the Catalog::registerField method to register 
// the enum field
#define DeclMember(A) \
       static const char *__get##A() { return #A; } \
       RegisterEnum<ClassType, A, &__get##A> __##A;

// And some of your code:
#define ENUM(Name, type, A, B, C) \
    struct Name : CatalogEnum<Name> { enum Type : type { A, B, C }; \
       DeclMember(A) \
       DeclMember(B) \
       DeclMember(C) \
       static Type fromString(const char * name) { return (Type)fromStringImpl(name); } \
       template <size_t N>
       static constexpr fromString(const char (&a)[N]); // Should iterate through all RegisterEnum  and call match_string(a) on them  
   [your actual code here]
   }; 


// Usage:
struct A
{
      ENUM(Color, int, Blue, Red, Green); // OMG, it works!

     void exampleMethod() { Color::Type c = Color::fromString("RED"); }
};
```

**Comment by aantron** [comment]
Thanks – I'll take a detailed look, but perhaps you can comment on my first impression. I considered similar approaches that declare static members, but didn't use them as explained below.

The ultimate underlying reason for why it seems hard to use my macro in a class is that it supports initializers. How would `DeclMember(A)` work if `A` was replaced by the tokens `B = 1`? I solved this by declaring an array and abusing operator overloading, both to make my macro expansion grammatical C++. The cost was needing to define that array (thus preventing sane usage inside classes).

**Comment by X-Ryl669** [comment]
The main trick problem I'm solving here, is how to execute "code" inside a declaration. The basic trick is to have the code done in a helper class' constructor (you'll have to add an instance of this class in your enum class). You can do whatever you want in such case. The fact that you're using (abusing?) macro for that prevent many things, like "A = 1,2,3" which is perfectly valid C++, but does not work in the macro, comma will make invalid code.

That being said, I wonder how you're extracting the "A" name in "A = B" case, but since you're successfully doing so, you can probably use my trick anyway. With constexpr string parsing, you can probably cut the "name" from the first space or '=' char at compile time, and still get the \_\_getMemberXName() right. It does not have to be called \_\_getA(), it can be called \_\_get345() with 345 being concatenation from \_\_get and \_\_LINE\_\_, as long as the code returns "A". The macro will have to be modified to fit in a single line obviously to get same \_\_LINE\_\_ on both `const char * CONCAT(__get, __LINE__) { return #A; }` and `RegisterEnum<ClassType, A=B, &CONCAT(__get, __LINE__)> CONCAT(__re,__LINE__);` part.

Notice that if the argument to the macro is "A=B" or "A=2", it'll work for the template RegisterEnum since the value will be extracted from the enum's just above in the declaration. The only thing that'll not work with my original code being the bad "argument" to "name" `#A` or `##A` in the macro, but this can be solved as described in the paragraph above with constexpr string fixing for `#A` and `CONCAT with __LINE__` for `##A`.

**Comment by aantron** [comment]
Actually, `A = (1,2,3)` works just fine. The preprocessor doesn't treat the comma as a separator when it is enclosed in parentheses like that. There are more complicated examples that might break, however. They are not very common. I am not sure what you mean by "preventing" things, actually, since supporting the initializer is actually *allowing* a syntax very similar to regular C++ enums, from the point of view of the user. From the point of view of the implementor, of course, it is preventing many things by constraining us considerably.

You're right about string extraction not being a problem.

I don't agree with the `__LINE__` approach. `__LINE__` will expand to the line (or one of the lines) on which the top-level macro is used, so it will be the same in the whole macro for each use. There are other ways to do this, such as enumeration.

**Comment by aantron** [comment]
So, how would the `constexpr` `fromString` work in this version? I can imagine a few ways to begin approaching this, but I'm curious if you have something specific in mind for iterating over the `RegisterEnum`s at compile time, such as generating a bunch of ternary operators.

**Comment by X-Ryl669** [comment]
Also, using this trick can make a O(1) search for name possible in compile time (in addition to O(1) search at runtime), with a very simple trick:
```
   // This should be out in your enum.h header
   constexpr unsigned int hash(const char *s, int off = 0) {                        
    return !s[off] ? 5381 : (hash(s, off+1)*33) ^ s[off];                           
   } 

#define BuildMapper(X) \
   template<unsigned int hash, int U>
   struct mapper { const int value = X; };


// Add this to the end of the DeclMember macro (template specialization):
   template<int U> \
   struct mapper<hash(cleanName(#A)), U> {const int value = A; };   


   // Add this to the my macro, in the struct Name declaration:
#define ENUM(...) // As before
   struct Name... // As before \
   // After DeclMember part:
   template <size_t N>
   constexpr Type from_string(const char (&s)[N]) { return mapper<hash(s), 0>::value; } // If compiler breaks here with struct mapper not found, then the string you've given does not exists in this enum
   
```
cleanName() is easy with a constexpr function, if you have "#A" that expand to "B = 1" then you'll have to write something like this:
```
constexpr const char * cleanName(const char * s, size_t off = 0) 
{ 
   if (!s[off] || s[off] == ' ' || s[off] == '=') { s[off] = 0; return s; } 
   return cleanName(s, off+1); 
} 
```
That might choke on s[off] = 0 part, in that case, the hash function will have to be modified to include a length limit that can be returned from the cleanName function instead (so not to hash longer than what cleanName returns)

**Comment by X-Ryl669** [comment]
You're right about __LINE__. Probably you can use a __COUNTER__ instead (which will increment after each usage). I need to test this, but I'm sure there is some solution (and likely using a mapper like in the previous comment registered by the __COUNTER__) like this:
```
template <int id>
struct ID2Name { static const char * getName() { return ""; } };

#define ID2NameSpec(N, A) \ 
   template<> struct ID2Name<N> { static const char * getName() { return #A; } } __i__##N;

// In macro DeclMember(A) : 
   ID2NameSpec(__COUNTER__, A);  // Use "&__i__0.getName" for registering instead
```

**Comment by X-Ryl669** [comment]
At the same time, I wonder if you'd accept multiline declaration for enum. I'm used to comment each field in the enum with doxygen, and it imposes one field per line. Your solution prevent me from doing so.
Maybe a multi-line version macro would be acceptable ?

**Comment by aantron** [comment]
One annoying problem with this is that it seems you will need two different functions for run-time and compile-time usage, since it's not possible for a template parameter `hash(s)` to depend on a non-`constexpr` `s`, and I'm not aware of a way to dispatch to different implementations based on whether some code is being run by the compiler or not.

Im not sure your code, in particular, compiles. I don't think the parameter in `s` would ever be `constexpr` in the body of `from_string`. I may be wrong, however. Can you give an example of how this function should be called, that compiles? There are other ways of doing this, but I think if this function doesn't compile with at least a string literal argument, we will be going down the road of painful usage syntax.

I'd also rather not split the interface into two, which is why I haven't done this kind of hashing yet. I've been considering doing it in an experimental branch, but I put it off while thinking of a better way (especially dispatching to different implementations, if at all possible).

As for `cleanName`, you're right. I already have a function like that and I use it pervasively.

**Comment by aantron** [comment]
A multi-line declaration is already possible with `\` (it's not really multi-line to the preprocessor, just like the macros you suggested, but it is visually multi-line). You have to use `/* */` comments inside it. I would be really surprised if Doxygen managed to produce anything sensible from it, however.

As for the counter suggestion, I already use counters like that for other purposes inside `enum.h`, so that's basically not a problem and it works. That's what I meant by enumeration. I have a higher-order macro that can call another macro for each of its arguments, also passing it a counter.

**Comment by X-Ryl669** [comment]
To detect if a value is a compile-time syntax, there are tricks also:
```
#define from_string_smart(s) \
    (__builtin_constant_p(s) && __builtin_constant_p(*s) ? \
        from_string_constexpr(s) : \
        from_string_runtime(s))
```

s will be a built-in constant inside from_string because I'm catching it as template<size_t N> select method. I need to compile this to make sure, but I'm 90% sure about it.

**Comment by aantron** [comment]
Well, I was able to compile your `from_string`, but not calls to it (on Clang).

As for the above, I am not sure if it's sufficient when supported, and then it's also not portable. One of the advantages of `enum.h` is that it's standard C++11, or standard C++98 + `__VA_ARGS__`. I could be convinced to use something like this, however, since it only matters on compilers that implement `constexpr` and that's only Clang, GCC, and MSVC2015.

**Comment by X-Ryl669** [comment]
http://ideone.com/Iotz4K  
for from_string successful compilation on C++11 compatible compiler (simplified not to include mapper).
I wonder the same kind of macro exists on Win32 compilers. 
It might not be an issue however, since the `template <size_t N>` will filter anyway the `const char[N]` from the `const char*` case (which will not be selected via SFINAE), so what will happen is:
```
    const char * s = gets();
    A::from_string(s);  // Calls from_string(const char * s) run time version
    A::from_string("abc"); // Calls from_string(const char [4]) instantiation of the version
```

**Comment by aantron** [comment]
Well it looks like you are editing this, so let me know when done :) In the meantime, I'll take a harder look at what's going on in my local version.

This will be an issue though (I think), because compile-time strings can have type `const char*`.

**Comment by X-Ryl669** [comment]
Sorry. I'm trying to get overload working between "const char&[N]" and "const char *". I'll let you know if I get something. Right now, let's say the compile_time version is "from_string_c" and the runtime version is "from_string", right ?

My work so far: http://ideone.com/sGBG1T

**Comment by aantron** [comment]
Yes, I got stuck on the same problem, but I didn't go ahead with solving it because there is another problem after that, that I think would need a very different solution from what we've had so far. I don't think you can instantiate a template based on the result of an expression that depends on a function parameter, because function parameters are never (?) `constexpr`. This is because the compiler does not know whether the `constexpr` function will be run at compile time or runtime for any given call, so it can't statically assume that the value is `constexpr` (i.e. provably compile-time).

**Comment by X-Ryl669** [comment]
Yes! I did it:
http://ideone.com/d5fdix

Basically, it's possible to compile-time detect whether we are calling `from_string("abc")` or `from_string(b)` (see code). So yes, it's possible to have O(1) behaviour in both compile-time and runtime  with 2 different function that'll be called depending if they are compile-time constant or not.

**Comment by aantron** [comment]
Nice. It still doesn't do the hash lookup, however. Both that, and the existing code, are complicated by this kind of compile-time string:

```
constexpr const char *bobby = "bobby";
printf("%u %u %u\n", Test<FromString(bobby)>::value, FromString("bobby"), FromString(b[0]));
```

That prints `0 198195889 0`. Right now, the code discriminates between string literals and other strings, but that's not exactly the same as the difference between compile-time strings and other strings.

**Comment by X-Ryl669** [comment]
For hash lookup, you'll have to do what I've written in my previous post with the mapper (that is a simple `template <unsigned hash, int value> mapper` that's specialized and instantiated by the compiler only for the field of the enum, the default template does not have the `value` member).

Concerning `constexpr const char *bobby = "bobby";`, first, I think it's not very common (most people will use the direct "bobby" argument, it's easier). 

However, in the ideone I've posted, there is a commented part that's able to detect whetever something is a constexpr. This needs to be combined with a new argument (bool) for the template's B in the code, in order to trigger the constexpr version of it.

I think it's doable at compile-time.

**Comment by aantron** [comment]
I'm still skeptical (I don't think it will work) that you can select a template instantiation based on a parameter of a `constexpr` function. I understand what you are suggesting with the template, I just don't think it will compile. I think you will have to make `from_string` either a template at its top level, or generate some kind of compile-time data structure out of the specialized templates in order to be able to do the hash lookup.

The latter is what I do (just not a hash table), but the data structure is represented as an array value, hence the limitation on using the macro inside a class. I'd be happy to use a better data structure, but I don't have one handy. I tried some compile-time sorts before, but the compilation time was abysmal, on the order of 50-100 times slower than the current implementation.

```cpp
#include <iostream>

template <int Hash>
struct entry { static const int value = 0; };

template <>
struct entry<0> { static const int value = 100; };

template <>
struct entry<15> { static const int value = 101; };

// The problem is here.
constexpr int lookup(const int &hash)
{
    return entry<hash>::value;
}

int main()
{
    // Ok.
    std::cout << entry<15>::value << std::endl;

    // Ok.
    const int hash = 15;
    std::cout << entry<hash>::value << std::endl;

    // You can't pass 15 through a function, even constexpr, and still use it as
    // a template parameter.
    std::cout << lookup(15) << std::endl;

    return 0;
}
```

**Comment by aantron** [comment]
**Status/summary**

My impression is that, while elements of this approach are promising, and are sometimes better than the current implementation in `enum.h`, we haven't been able to get it to work well for all cases – specifically, compile-time usage with `constexpr` functions.

The two main ways forward I see at this point are (1) switching to an alternative interface based on templates for compile-time usage, and (2) generating some kind of nested ternary expression for the `constexpr` `from_string` function. There are other variations, but I am focusing on the ones mentioned above. Regarding each:

1. The template interface permanently forks the interface into two, since templates cannot be applied to non-constant values. I would rather avoid this. Besides that, a template can't be applied reasonably to some constant values that `constexpr` functions accept, such as `const char*`s. These are important, because they, and not only `char` arrays, and especially not literals, are likely to arise in `constexpr` metaprogramming.
2. This can work, but I have doubts about the compilation speed, and I'm not sure if it's worth the extra code complexity, since `enum.h` will have to generate a separate ternary expression for each kind of lookup that it currently does on the arrays. It will also have to generate some kind of expression that allows ordered traversal like current arrays do. We might also have to put it in some effort into supporting random access. Doing all that doesn't seem, to me at this point, to be worth the benefit of being able to declare enums inside classes. I also have doubts about the speed of the generated code for some operations.

If you agree with the above, I will close the issue in one day – but let me know if you have other ideas. And, if you think of something later, feel free to mention it here and we can re-open.
