### ISSUE TITLE
Opt-in feature to avoid need for + in x == +MyEnum::SomeValue

### ISSUE THREAD

**Issue by alexeyr** [aantron/better-enums#89]
> In some cases, it is necessary to prefix constants such as Channel::Red with a + to explicitly promote them to type Channel. For example, if you are doing a comparison:

>     channel == +Channel::Red

Would it be possible to go the other way around so `Channel::Red` is a `Channel` by default? And presumably it would apply for
```
// Strict variant
switch (channel) {
    case +Channel::Red:   break;
    case +Channel::Green: break;
    case +Channel::Blue:  break;
}
```
from http://aantron.github.io/better-enums/OptInFeatures.html as well.

**Comment by aantron** [comment]
I would have to explore it again in fully modern C++ to answer, or I would accept an exploratory PR :) The original design was still trying to being compatible with C++98, probably not a priority at this point.

If keeping compatibility with C++98, however, I recall that the answer was no, since `Channel::Red` was literally a C++98 non-typesafe enum, and could only be used as a `Channel` by implicit conversion, and that conversion was ambiguous in many practical situations.

**Comment by alexeyr** [comment]
I decided it was annoying enough for me to go with [wise_enum](https://github.com/quicknir/wise_enum/) instead (not magic_enum because no C++17 on the project) :) It might be worth recommending alongside magic_enum actually. This can be closed if you prefer.

**Comment by aantron** [comment]
I think, given #88, I will remove links to other enum libraries from the README, as there now seem to be enough that they should be discoverable on their own. After reading the wise_enum README, I'm aware of magic_enum, wise_enum, and meta_enum.

Some of these seem to be at least spiritually derived from Better Enums (though they are substantially different). I'm vaguely glad to see this project help spawn them :)
